name: test2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.0
  path: ^1.9.0
  sqflite_common_ffi: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/favicon.png

flutter_icons:
  android: true
  ios: true
  image_path: "asset/favicon.png"
  adaptive_icon:
    foreground: "asset/favicon.png"
    background: "#FFFFFF"
